<a href="https://colab.research.google.com/github/MachineLearnia/Python-Machine-Learning/blob/master/10%20-%20Numpy%20(les%20Bases).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 10/30 Numpy : Tableau ndarray

In [1]:
import numpy as np

## 1. Générateurs de tableaux **ndarray**
- générateur par défaut : **ndarray()**
- générateur 1D : **np.linspace** et **np.arange()**
- générateur ND : **np.zeros()**, **np.ones()**, **np.random.randn()** (ce sont les plus utiles)

In [2]:
A = np.array([1, 2, 3]) # générateur par défaut, qui permet de convertir des listes (ou autres objets) en tableau ndarray
A = np.zeros((2, 3)) # tableau de 0 aux dimensions 2x3
print(A)
B = np.ones((2, 3)) # tableau de 1 aux dimensions 2x3
C = np.random.randn(2, 3) # tableau aléatoire (distribution normale) aux dimensions 2x3
D = np.random.rand(2, 3) # tableau aléatoire (distribution uniforme)
 
E = np.random.randint(0, 10, [2, 3]) # tableau d'entiers aléatoires de 0 a 10 et de dimension 2x3

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
A = np.ones((2, 3), dtype=np.float16) # définit le type et la place a occuper sur la mémoire
B = np.eye(4, dtype=np.bool) # créer une matrice identité et convertit les éléments en type bool.

C:\Users\user\AppData\Local\Temp\ipykernel_3928\950731242.py:2: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  B = np.eye(4, dtype=np.bool) # créer une matrice identité et convertit les éléments en type bool.


In [4]:
A = np.linspace(1, 10, 5)
print(A)
B = np.arange(0, 10, 5)
print(B)

[ 1.    3.25  5.5   7.75 10.  ]
[0 5]


## 2. Attributs importants
- size
- shape

In [5]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
 
print(A.size) # le nombre d'éléments dans le tableau A
print(A.shape) # les dimensions du tableau A (sous forme de Tuple)
 
print(type(A.shape)) # voici la preuve que la shape est un tuple
 
print(A.shape[0]) # le nombre d'éléments dans la premiere dimension de A

6
(2, 3)
<class 'tuple'>
2


## 3. Méthodes importantes
- **reshape()** : pour redimensionner un tableau
- **ravel()** : pour applatir un tableau (qu'il ne fasse plus qu'une dimension)
- **squeeze()** : quand une dimension est égale a 1, cette dimension disparait
- **concatenate()** : assemble 2 tableaux ensemble selon un axes (existe aussi en hstack et vstack)

In [6]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
 
A = A.reshape((3, 2)) # redimensionne le tableau A (3 lignes, 2 colonnes)
A.ravel() # Aplatit le tableau A (une seule dimension)
A.squeeze() # élimine les dimensions "1" de A.

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
B = np.ones((2, 3)) # création d'un tableau de shape (2, 3)

np.concatenate((A, B), axis=0) # axe 0 : équivalent de np.vstack((A, B))

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.concatenate((A, B), axis=1) # axe 1 : équivalent de np.hstack((A, B))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

## 4. Exercice et Solutions

In [9]:
def initialisation(m, n):
    # m : nombre de lignes
    # n : nombre de colonnes
    # retourne une matrice aléatoire (m, n+1)
    # avec une colonne biais (remplie de "1") tout a droite

    return X

In [10]:
# SOLUTION
def initialisation(m, n):
    # m : nombre de lignes
    # n : nombre de colonnes
    # retourne une matrice aléatoire (m, n+1)
    # avec une colonne biais (remplie de "1") tout a droite
    X = np.random.randn(m, n)
    X = np.concatenate((X, np.ones((X.shape[0], 1))), axis = 1)

    return X

initialisation(3, 4)

array([[-0.49471115, -0.8481197 , -0.4391063 ,  1.02573248,  1.        ],
       [ 0.85470102,  0.66292758,  0.36428705, -0.62454556,  1.        ],
       [-0.91239047, -0.67233301, -0.75837831, -0.86947174,  1.        ]])